### ISSUE TITLE
Switch front-end building into using Webpack

### ISSUE THREAD

**Issue by obscurage** [hep7agon/cfh-ui#34]
Gulp/Browserify is an alternative which should be discussed.

Separate the different react.js components into different JavaScript-files
I.e.
- list of feedbacks view/page has only components linked to the page
- map page has own components
- later on give feedback has own components
- switch using ES6 in React.js component declarations

**Comment by sevesalm** [comment]
We want to do this to speed up rebundling:

https://christianalfoni.github.io/react-webpack-cookbook/Optimizing-rebundling.html
