### ISSUE TITLE
Produce installation documentation for Webpack

### ISSUE THREAD

**Issue by obscurage** [hep7agon/cfh-ui#45]
A documentation is required in which the installation and running of the development environment are described.

Ready when:
- instructions are written and proven to be working

Related issue:
#34

**Comment by sevesalm** [comment]
I already wrote a documentation. Here it is, in the `README.md` of the branch `webpack`:

https://github.com/hep7agon/cfh-ui/tree/webpack

I'll add more details as needed.

**Comment by obscurage** [comment]
Installation documentation included in the `README.md` -file of `master` branch!
Works also.
